/*
* Generated file
*
* Generated from: yang module name: cluster-admin-provider yang module local name: cluster-admin-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jan 20 12:00:09 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.cluster_admin_provider;
public class ClusterAdminProviderModuleFactory extends org.opendaylight.controller.config.yang.config.cluster_admin_provider.AbstractClusterAdminProviderModuleFactory {

}
