/*
* Generated file
*
* Generated from: yang module name: bundles-service-impl yang module local name: bundles-service-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jan 21 13:26:48 EST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.bundle_service.impl;
public class BundleServiceImplModuleFactory extends org.opendaylight.controller.config.yang.config.bundle_service.impl.AbstractBundleServiceImplModuleFactory {

}
