/**
 * Generated file

 * Generated from: yang module name: config-test-impl  yang module local name: impl-dep
 * Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
 * Generated at: Fri Sep 27 13:02:28 CEST 2013
 *
 * Do not modify this file unless it is present under src/main directory
 */
package org.opendaylight.controller.config.yang.test.impl;

/**
*
*/
public class DepTestImplModuleFactory
        extends
        org.opendaylight.controller.config.yang.test.impl.AbstractDepTestImplModuleFactory {

}
