/*
* Generated file
*
* Generated from: yang module name: opendaylight-rest-docgen yang module local name: rest-docgen-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jul 29 12:57:36 CEST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.rest.docgen;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.opendaylight.controller.config.api.ModuleIdentifier;
import org.osgi.framework.BundleContext;

public class RestDocgenModuleFactory extends org.opendaylight.controller.config.yang.md.sal.rest.docgen.AbstractRestDocgenModuleFactory {

    @Override
    public RestDocgenModule instantiateModule(final String instanceName,
                                                 final DependencyResolver dependencyResolver, final RestDocgenModule oldModule,
                                                 final AutoCloseable oldInstance, final BundleContext bundleContext) {
        return new RestDocgenModule(new ModuleIdentifier(NAME, instanceName), dependencyResolver, oldModule,
                oldInstance, bundleContext);
    }

    @Override
    public RestDocgenModule instantiateModule(final String instanceName,
                                                 final DependencyResolver dependencyResolver, final BundleContext bundleContext) {
        return new RestDocgenModule(new ModuleIdentifier(NAME, instanceName), dependencyResolver, bundleContext);
    }
}
