/**
* Generated file

* Generated from: yang module name: opendaylight-sal-dom-broker-impl  yang module local name: dom-broker-impl-singleton
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Nov 18 14:48:19 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.dom.impl;

import org.opendaylight.controller.sal.dom.broker.BrokerConfigActivator;
import org.opendaylight.controller.sal.dom.broker.BrokerImpl;
import org.osgi.framework.BundleContext;

/**
*
*/
public final class DomBrokerImplSingletonModule extends org.opendaylight.controller.config.yang.md.sal.dom.impl.AbstractDomBrokerImplSingletonModule
{

    private BundleContext bundleContext;

    public DomBrokerImplSingletonModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver) {
        super(identifier, dependencyResolver);
    }

    public DomBrokerImplSingletonModule(org.opendaylight.controller.config.api.ModuleIdentifier identifier, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, DomBrokerImplSingletonModule oldModule, java.lang.AutoCloseable oldInstance) {
        super(identifier, dependencyResolver, oldModule, oldInstance);
    }

    @Override
    public void validate(){
        super.validate();
    }

    @Override
    public java.lang.AutoCloseable createInstance() {
        BrokerImpl broker = new BrokerImpl();
        broker.setBundleContext(bundleContext);
        BrokerConfigActivator activator = new BrokerConfigActivator();
        broker.setDeactivator(activator);
        activator.start(broker,bundleContext);
        return broker;
    }

    public void setBundleContext(BundleContext bundleContext) {
        this.bundleContext = bundleContext;
    }
}
