/*
* Generated file
*
* Generated from: yang module name: odl-concurrent-data-broker-cfg yang module local name: dom-concurrent-data-broker
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jan 20 12:00:09 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.concurrent_data_broker;
public class DomConcurrentDataBrokerModuleFactory extends org.opendaylight.controller.config.yang.config.concurrent_data_broker.AbstractDomConcurrentDataBrokerModuleFactory {

}
