/*
* Generated file
*
* Generated from: yang module name: cluster-config-provider yang module local name: cluster-config-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jan 20 12:00:09 CET 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.cluster_config_provider;
public class ClusterConfigProviderModuleFactory extends org.opendaylight.controller.config.yang.config.cluster_config_provider.AbstractClusterConfigProviderModuleFactory {

}
