<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.opendaylight.controller</groupId>
        <artifactId>bnd-parent</artifactId>
        <version>14.0.0</version>
        <relativePath>../../bnd-parent/pom.xml</relativePath>
    </parent>

    <artifactId>jmx-core</artifactId>
    <packaging>jar</packaging>
    <name>${project.artifactId}</name>
    <description>Core JMX integration</description>

    <properties>
        <!-- FIXME: fix these up and set maven.javadoc.failOnWarnings=true -->
        <doclint>all,-missing</doclint>
        <odlparent.dependency.enforce>true</odlparent.dependency.enforce>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.jdt</groupId>
            <artifactId>org.eclipse.jdt.annotation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.opendaylight.yangtools</groupId>
            <artifactId>util</artifactId>
        </dependency>
    </dependencies>
</project>
