<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.opendaylight.controller</groupId>
        <artifactId>binding-parent</artifactId>
        <version>14.0.2-SNAPSHOT</version>
        <relativePath>../../binding-parent/pom.xml</relativePath>
    </parent>

    <artifactId>cds-types</artifactId>
    <packaging>bundle</packaging>
    <description>Java bindings for odl-controller-cds-types.yang</description>

    <properties>
        <maven.javadoc.failOnWarnings>true</maven.javadoc.failOnWarnings>
        <odlparent.dependency.enforce>true</odlparent.dependency.enforce>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.jdt</groupId>
            <artifactId>org.eclipse.jdt.annotation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.opendaylight.yangtools</groupId>
            <artifactId>yang-common</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.felix</groupId>
                <artifactId>maven-bundle-plugin</artifactId>
                <configuration>
                    <instructions>
                        <Automatic-Module-Name>org.opendaylight.controller.model.cds.types</Automatic-Module-Name>
                    </instructions>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
