/*
* Generated file
*
* Generated from: yang module name: clustering-service-provider yang module local name: clustering-service-provider
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Apr 30 17:46:49 PDT 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.clustering_service_provider;
public class SalClusteringServiceProviderModuleFactory extends org.opendaylight.controller.config.yang.config.clustering_service_provider.AbstractSalClusteringServiceProviderModuleFactory {

}
