/**
* Generated file

* Generated from: yang module name: nsos-threadpool  yang module local name: netty-threadgroup-fixed
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Nov 08 08:31:45 CET 2013
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.netty.threadgroup;

/**
*
*/
public class NettyThreadgroupModuleFactory extends org.opendaylight.controller.config.yang.netty.threadgroup.AbstractNettyThreadgroupModuleFactory
{


}
