// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MockPayload.proto

package org.opendaylight.controller.protobuff.messages.cluster.raft.test;

public final class MockPayloadMessages {
  private MockPayloadMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(org.opendaylight.controller.protobuff.messages.cluster.raft.test.MockPayloadMessages.value);
  }
  public static final int VALUE_FIELD_NUMBER = 2;
  /**
   * <code>extend .org.opendaylight.controller.cluster.raft.AppendEntries.ReplicatedLogEntry.Payload { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      org.opendaylight.controller.protobuff.messages.cluster.raft.AppendEntriesMessages.AppendEntries.ReplicatedLogEntry.Payload,
      java.lang.String> value = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MockPayload.proto\022-org.opendaylight.co" +
      "ntroller.cluster.raft.test\032\033AppendEntrie" +
      "sMessages.proto:a\n\005value\022R.org.opendayli" +
      "ght.controller.cluster.raft.AppendEntrie" +
      "s.ReplicatedLogEntry.Payload\030\002 \001(\tBW\n@or" +
      "g.opendaylight.controller.protobuff.mess" +
      "ages.cluster.raft.testB\023MockPayloadMessa" +
      "ges"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          value.internalInit(descriptor.getExtensions().get(0));
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.opendaylight.controller.protobuff.messages.cluster.raft.AppendEntriesMessages.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
