/*
* Generated file
*
* Generated from: yang module name: toaster-provider-impl yang module local name: icmp-discovery-provider-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu May 15 10:50:45 EDT 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.icmp.provider.impl;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.opendaylight.controller.config.api.DynamicMBeanWithInstance;
import org.opendaylight.controller.config.spi.Module;
import org.osgi.framework.BundleContext;

public class IcmpDiscoveryProviderModuleFactory extends org.opendaylight.controller.config.yang.config.icmp.provider.impl.AbstractIcmpDiscoveryProviderModuleFactory {

    @Override
    public Module createModule(String instanceName, DependencyResolver dependencyResolver,
            DynamicMBeanWithInstance old, BundleContext bundleContext) throws Exception {
        IcmpDiscoveryProviderModule module = (IcmpDiscoveryProviderModule) super.createModule(instanceName, dependencyResolver,
                old, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

    @Override
    public Module createModule(String instanceName, DependencyResolver dependencyResolver, BundleContext bundleContext) {
        IcmpDiscoveryProviderModule module = (IcmpDiscoveryProviderModule) super.createModule(instanceName, dependencyResolver,
                bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

}
