/*
* Generated file
*
* Generated from: yang module name: features-service-impl yang module local name: features-service-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Jan 19 12:06:35 EST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.features_service.impl;
public class FeaturesServiceImplModuleFactory extends org.opendaylight.controller.config.yang.config.features_service.impl.AbstractFeaturesServiceImplModuleFactory {

}
