/**
* Generated file

* Generated from: yang module name: opendaylight-sal-restconf-broker-impl  yang module local name: restconf-broker-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Feb 10 15:32:31 CET 2014
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.restconf.broker;

/**
*
*/
public class SalRemoteServiceBrokerModuleFactory extends org.opendaylight.controller.config.yang.md.sal.restconf.broker.AbstractSalRemoteServiceBrokerModuleFactory
{


}
